version: '2'
services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - laravel
    ports:
      - "8090:80"
    volumes:
      - ./app:/app
    environment:
      - PHP_IDE_CONFIG=localhost
      - XDEBUG_CONFIG='remote_host=10.254.254.254 remote_port=9001'
    links:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'laravel'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'laravel'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'laravel'
    networks:
      - laravel
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
networks:
  laravel:
    external: false