version: '2'
services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
    restart: always
    networks:
      - laravel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
    environment:
      - PHP_IDE_CONFIG=serverName=laravel.local
      - RAPID_API_KEY=8bd20fd0-5f30-11ea-ab28-bb673dd95e9c
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl xdebug'
    links:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'api_provider'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'api_provider'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'laravel'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'n7ftRp8VCkm'
    networks:
      - laravel
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
networks:
  laravel:
    external: false