<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        DB::table('countries')->insert(['country_name' => "Afghanistan", 'country_iso2' => 'AF']);
        DB::table('countries')->insert(['country_name' => "Ã…land Islands", 'country_iso2' => 'AX']);
        DB::table('countries')->insert(['country_name' => "Albania", 'country_iso2' => 'AL']);
        DB::table('countries')->insert(['country_name' => "Algeria", 'country_iso2' => 'DZ']);
        DB::table('countries')->insert(['country_name' => "American Samoa", 'country_iso2' => 'AS']);
        DB::table('countries')->insert(['country_name' => "Andorra", 'country_iso2' => 'AD']);
        DB::table('countries')->insert(['country_name' => "Angola", 'country_iso2' => 'AO']);
        DB::table('countries')->insert(['country_name' => "Anguilla", 'country_iso2' => 'AI']);
        DB::table('countries')->insert(['country_name' => "Antarctica", 'country_iso2' => 'AQ']);
        DB::table('countries')->insert(['country_name' => "Antigua and Barbuda", 'country_iso2' => 'AG']);
        DB::table('countries')->insert(['country_name' => "Argentina", 'country_iso2' => 'AR']);
        DB::table('countries')->insert(['country_name' => "Armenia", 'country_iso2' => 'AM']);
        DB::table('countries')->insert(['country_name' => "Aruba", 'country_iso2' => 'AW']);
        DB::table('countries')->insert(['country_name' => "Australia", 'country_iso2' => 'AU']);
        DB::table('countries')->insert(['country_name' => "Austria", 'country_iso2' => 'AT']);
        DB::table('countries')->insert(['country_name' => "Azerbaijan", 'country_iso2' => 'AZ']);
        DB::table('countries')->insert(['country_name' => "Bahamas", 'country_iso2' => 'BS']);
        DB::table('countries')->insert(['country_name' => "Bahrain", 'country_iso2' => 'BH']);
        DB::table('countries')->insert(['country_name' => "Bangladesh", 'country_iso2' => 'BD']);
        DB::table('countries')->insert(['country_name' => "Barbados", 'country_iso2' => 'BB']);
        DB::table('countries')->insert(['country_name' => "Belarus", 'country_iso2' => 'BY']);
        DB::table('countries')->insert(['country_name' => "Belgium", 'country_iso2' => 'BE']);
        DB::table('countries')->insert(['country_name' => "Belize", 'country_iso2' => 'BZ']);
        DB::table('countries')->insert(['country_name' => "Benin", 'country_iso2' => 'BJ']);
        DB::table('countries')->insert(['country_name' => "Bermuda", 'country_iso2' => 'BM']);
        DB::table('countries')->insert(['country_name' => "Bhutan", 'country_iso2' => 'BT']);
        DB::table('countries')->insert(['country_name' => "Bolivia, Plurinational State of", 'country_iso2' => 'BO']);
        DB::table('countries')->insert(['country_name' => "Bonaire, Sint Eustatius and Saba", 'country_iso2' => 'BQ']);
        DB::table('countries')->insert(['country_name' => "Bosnia and Herzegovina", 'country_iso2' => 'BA']);
        DB::table('countries')->insert(['country_name' => "Botswana", 'country_iso2' => 'BW']);
        DB::table('countries')->insert(['country_name' => "Bouvet Island", 'country_iso2' => 'BV']);
        DB::table('countries')->insert(['country_name' => "Brazil", 'country_iso2' => 'BR']);
        DB::table('countries')->insert(['country_name' => "British Indian Ocean Territory", 'country_iso2' => 'IO']);
        DB::table('countries')->insert(['country_name' => "Brunei Darussalam", 'country_iso2' => 'BN']);
        DB::table('countries')->insert(['country_name' => "Bulgaria", 'country_iso2' => 'BG']);
        DB::table('countries')->insert(['country_name' => "Burkina Faso", 'country_iso2' => 'BF']);
        DB::table('countries')->insert(['country_name' => "Burundi", 'country_iso2' => 'BI']);
        DB::table('countries')->insert(['country_name' => "Cambodia", 'country_iso2' => 'KH']);
        DB::table('countries')->insert(['country_name' => "Cameroon", 'country_iso2' => 'CM']);
        DB::table('countries')->insert(['country_name' => "Canada", 'country_iso2' => 'CA']);
        DB::table('countries')->insert(['country_name' => "Cape Verde", 'country_iso2' => 'CV']);
        DB::table('countries')->insert(['country_name' => "Cayman Islands", 'country_iso2' => 'KY']);
        DB::table('countries')->insert(['country_name' => "Central African Republic", 'country_iso2' => 'CF']);
        DB::table('countries')->insert(['country_name' => "Chad", 'country_iso2' => 'TD']);
        DB::table('countries')->insert(['country_name' => "Chile", 'country_iso2' => 'CL']);
        DB::table('countries')->insert(['country_name' => "China", 'country_iso2' => 'CN']);
        DB::table('countries')->insert(['country_name' => "Christmas Island", 'country_iso2' => 'CX']);
        DB::table('countries')->insert(['country_name' => "Cocos (Keeling) Islands", 'country_iso2' => 'CC']);
        DB::table('countries')->insert(['country_name' => "Colombia", 'country_iso2' => 'CO']);
        DB::table('countries')->insert(['country_name' => "Comoros", 'country_iso2' => 'KM']);
        DB::table('countries')->insert(['country_name' => "Congo", 'country_iso2' => 'CG']);
        DB::table('countries')->insert(['country_name' => "Congo, the Democratic Republic of the", 'country_iso2' => 'CD']);
        DB::table('countries')->insert(['country_name' => "Cook Islands", 'country_iso2' => 'CK']);
        DB::table('countries')->insert(['country_name' => "Costa Rica", 'country_iso2' => 'CR']);
        DB::table('countries')->insert(['country_name' => "CÃ´te d'Ivoire", 'country_iso2' => 'CI']);
        DB::table('countries')->insert(['country_name' => "Croatia", 'country_iso2' => 'HR']);
        DB::table('countries')->insert(['country_name' => "Cuba", 'country_iso2' => 'CU']);
        DB::table('countries')->insert(['country_name' => "CuraÃ§ao", 'country_iso2' => 'CW']);
        DB::table('countries')->insert(['country_name' => "Cyprus", 'country_iso2' => 'CY']);
        DB::table('countries')->insert(['country_name' => "Czech Republic", 'country_iso2' => 'CZ']);
        DB::table('countries')->insert(['country_name' => "Denmark", 'country_iso2' => 'DK']);
        DB::table('countries')->insert(['country_name' => "Djibouti", 'country_iso2' => 'DJ']);
        DB::table('countries')->insert(['country_name' => "Dominica", 'country_iso2' => 'DM']);
        DB::table('countries')->insert(['country_name' => "Dominican Republic", 'country_iso2' => 'DO']);
        DB::table('countries')->insert(['country_name' => "Ecuador", 'country_iso2' => 'EC']);
        DB::table('countries')->insert(['country_name' => "Egypt", 'country_iso2' => 'EG']);
        DB::table('countries')->insert(['country_name' => "El Salvador", 'country_iso2' => 'SV']);
        DB::table('countries')->insert(['country_name' => "Equatorial Guinea", 'country_iso2' => 'GQ']);
        DB::table('countries')->insert(['country_name' => "Eritrea", 'country_iso2' => 'ER']);
        DB::table('countries')->insert(['country_name' => "Estonia", 'country_iso2' => 'EE']);
        DB::table('countries')->insert(['country_name' => "Ethiopia", 'country_iso2' => 'ET']);
        DB::table('countries')->insert(['country_name' => "Falkland Islands (Malvinas)", 'country_iso2' => 'FK']);
        DB::table('countries')->insert(['country_name' => "Faroe Islands", 'country_iso2' => 'FO']);
        DB::table('countries')->insert(['country_name' => "Fiji", 'country_iso2' => 'FJ']);
        DB::table('countries')->insert(['country_name' => "Finland", 'country_iso2' => 'FI']);
        DB::table('countries')->insert(['country_name' => "France", 'country_iso2' => 'FR']);
        DB::table('countries')->insert(['country_name' => "French Guiana", 'country_iso2' => 'GF']);
        DB::table('countries')->insert(['country_name' => "French Polynesia", 'country_iso2' => 'PF']);
        DB::table('countries')->insert(['country_name' => "French Southern Territories", 'country_iso2' => 'TF']);
        DB::table('countries')->insert(['country_name' => "Gabon", 'country_iso2' => 'GA']);
        DB::table('countries')->insert(['country_name' => "Gambia", 'country_iso2' => 'GM']);
        DB::table('countries')->insert(['country_name' => "Georgia", 'country_iso2' => 'GE']);
        DB::table('countries')->insert(['country_name' => "Germany", 'country_iso2' => 'DE']);
        DB::table('countries')->insert(['country_name' => "Ghana", 'country_iso2' => 'GH']);
        DB::table('countries')->insert(['country_name' => "Gibraltar", 'country_iso2' => 'GI']);
        DB::table('countries')->insert(['country_name' => "Greece", 'country_iso2' => 'GR']);
        DB::table('countries')->insert(['country_name' => "Greenland", 'country_iso2' => 'GL']);
        DB::table('countries')->insert(['country_name' => "Grenada", 'country_iso2' => 'GD']);
        DB::table('countries')->insert(['country_name' => "Guadeloupe", 'country_iso2' => 'GP']);
        DB::table('countries')->insert(['country_name' => "Guam", 'country_iso2' => 'GU']);
        DB::table('countries')->insert(['country_name' => "Guatemala", 'country_iso2' => 'GT']);
        DB::table('countries')->insert(['country_name' => "Guernsey", 'country_iso2' => 'GG']);
        DB::table('countries')->insert(['country_name' => "Guinea", 'country_iso2' => 'GN']);
        DB::table('countries')->insert(['country_name' => "Guinea-Bissau", 'country_iso2' => 'GW']);
        DB::table('countries')->insert(['country_name' => "Guyana", 'country_iso2' => 'GY']);
        DB::table('countries')->insert(['country_name' => "Haiti", 'country_iso2' => 'HT']);
        DB::table('countries')->insert(['country_name' => "Heard Island and McDonald Islands", 'country_iso2' => 'HM']);
        DB::table('countries')->insert(['country_name' => "Holy See (Vatican City State)", 'country_iso2' => 'VA']);
        DB::table('countries')->insert(['country_name' => "Honduras", 'country_iso2' => 'HN']);
        DB::table('countries')->insert(['country_name' => "Hong Kong", 'country_iso2' => 'HK']);
        DB::table('countries')->insert(['country_name' => "Hungary", 'country_iso2' => 'HU']);
        DB::table('countries')->insert(['country_name' => "Iceland", 'country_iso2' => 'IS']);
        DB::table('countries')->insert(['country_name' => "India", 'country_iso2' => 'IN']);
        DB::table('countries')->insert(['country_name' => "Indonesia", 'country_iso2' => 'ID']);
        DB::table('countries')->insert(['country_name' => "Iran, Islamic Republic of", 'country_iso2' => 'IR']);
        DB::table('countries')->insert(['country_name' => "Iraq", 'country_iso2' => 'IQ']);
        DB::table('countries')->insert(['country_name' => "Ireland", 'country_iso2' => 'IE']);
        DB::table('countries')->insert(['country_name' => "Isle of Man", 'country_iso2' => 'IM']);
        DB::table('countries')->insert(['country_name' => "Israel", 'country_iso2' => 'IL']);
        DB::table('countries')->insert(['country_name' => "Italy", 'country_iso2' => 'IT']);
        DB::table('countries')->insert(['country_name' => "Jamaica", 'country_iso2' => 'JM']);
        DB::table('countries')->insert(['country_name' => "Japan", 'country_iso2' => 'JP']);
        DB::table('countries')->insert(['country_name' => "Jersey", 'country_iso2' => 'JE']);
        DB::table('countries')->insert(['country_name' => "Jordan", 'country_iso2' => 'JO']);
        DB::table('countries')->insert(['country_name' => "Kazakhstan", 'country_iso2' => 'KZ']);
        DB::table('countries')->insert(['country_name' => "Kenya", 'country_iso2' => 'KE']);
        DB::table('countries')->insert(['country_name' => "Kiribati", 'country_iso2' => 'KI']);
        DB::table('countries')->insert(['country_name' => "Korea, Democratic People's Republic of", 'country_iso2' => 'KP']);
        DB::table('countries')->insert(['country_name' => "Korea, Republic of", 'country_iso2' => 'KR']);
        DB::table('countries')->insert(['country_name' => "Kuwait", 'country_iso2' => 'KW']);
        DB::table('countries')->insert(['country_name' => "Kyrgyzstan", 'country_iso2' => 'KG']);
        DB::table('countries')->insert(['country_name' => "Lao People's Democratic Republic", 'country_iso2' => 'LA']);
        DB::table('countries')->insert(['country_name' => "Latvia", 'country_iso2' => 'LV']);
        DB::table('countries')->insert(['country_name' => "Lebanon", 'country_iso2' => 'LB']);
        DB::table('countries')->insert(['country_name' => "Lesotho", 'country_iso2' => 'LS']);
        DB::table('countries')->insert(['country_name' => "Liberia", 'country_iso2' => 'LR']);
        DB::table('countries')->insert(['country_name' => "Libya", 'country_iso2' => 'LY']);
        DB::table('countries')->insert(['country_name' => "Liechtenstein", 'country_iso2' => 'LI']);
        DB::table('countries')->insert(['country_name' => "Lithuania", 'country_iso2' => 'LT']);
        DB::table('countries')->insert(['country_name' => "Luxembourg", 'country_iso2' => 'LU']);
        DB::table('countries')->insert(['country_name' => "Macao", 'country_iso2' => 'MO']);
        DB::table('countries')->insert(['country_name' => "Macedonia, the Former Yugoslav Republic of", 'country_iso2' => 'MK']);
        DB::table('countries')->insert(['country_name' => "Madagascar", 'country_iso2' => 'MG']);
        DB::table('countries')->insert(['country_name' => "Malawi", 'country_iso2' => 'MW']);
        DB::table('countries')->insert(['country_name' => "Malaysia", 'country_iso2' => 'MY']);
        DB::table('countries')->insert(['country_name' => "Maldives", 'country_iso2' => 'MV']);
        DB::table('countries')->insert(['country_name' => "Mali", 'country_iso2' => 'ML']);
        DB::table('countries')->insert(['country_name' => "Malta", 'country_iso2' => 'MT']);
        DB::table('countries')->insert(['country_name' => "Marshall Islands", 'country_iso2' => 'MH']);
        DB::table('countries')->insert(['country_name' => "Martinique", 'country_iso2' => 'MQ']);
        DB::table('countries')->insert(['country_name' => "Mauritania", 'country_iso2' => 'MR']);
        DB::table('countries')->insert(['country_name' => "Mauritius", 'country_iso2' => 'MU']);
        DB::table('countries')->insert(['country_name' => "Mayotte", 'country_iso2' => 'YT']);
        DB::table('countries')->insert(['country_name' => "Mexico", 'country_iso2' => 'MX']);
        DB::table('countries')->insert(['country_name' => "Micronesia, Federated States of", 'country_iso2' => 'FM']);
        DB::table('countries')->insert(['country_name' => "Moldova, Republic of", 'country_iso2' => 'MD']);
        DB::table('countries')->insert(['country_name' => "Monaco", 'country_iso2' => 'MC']);
        DB::table('countries')->insert(['country_name' => "Mongolia", 'country_iso2' => 'MN']);
        DB::table('countries')->insert(['country_name' => "Montenegro", 'country_iso2' => 'ME']);
        DB::table('countries')->insert(['country_name' => "Montserrat", 'country_iso2' => 'MS']);
        DB::table('countries')->insert(['country_name' => "Morocco", 'country_iso2' => 'MA']);
        DB::table('countries')->insert(['country_name' => "Mozambique", 'country_iso2' => 'MZ']);
        DB::table('countries')->insert(['country_name' => "Myanmar", 'country_iso2' => 'MM']);
        DB::table('countries')->insert(['country_name' => "Namibia", 'country_iso2' => 'NA']);
        DB::table('countries')->insert(['country_name' => "Nauru", 'country_iso2' => 'NR']);
        DB::table('countries')->insert(['country_name' => "Nepal", 'country_iso2' => 'NP']);
        DB::table('countries')->insert(['country_name' => "Netherlands", 'country_iso2' => 'NL']);
        DB::table('countries')->insert(['country_name' => "New Caledonia", 'country_iso2' => 'NC']);
        DB::table('countries')->insert(['country_name' => "New Zealand", 'country_iso2' => 'NZ']);
        DB::table('countries')->insert(['country_name' => "Nicaragua", 'country_iso2' => 'NI']);
        DB::table('countries')->insert(['country_name' => "Niger", 'country_iso2' => 'NE']);
        DB::table('countries')->insert(['country_name' => "Nigeria", 'country_iso2' => 'NG']);
        DB::table('countries')->insert(['country_name' => "Niue", 'country_iso2' => 'NU']);
        DB::table('countries')->insert(['country_name' => "Norfolk Island", 'country_iso2' => 'NF']);
        DB::table('countries')->insert(['country_name' => "Northern Mariana Islands", 'country_iso2' => 'MP']);
        DB::table('countries')->insert(['country_name' => "Norway", 'country_iso2' => 'NO']);
        DB::table('countries')->insert(['country_name' => "Oman", 'country_iso2' => 'OM']);
        DB::table('countries')->insert(['country_name' => "Pakistan", 'country_iso2' => 'PK']);
        DB::table('countries')->insert(['country_name' => "Palau", 'country_iso2' => 'PW']);
        DB::table('countries')->insert(['country_name' => "Palestine, State of", 'country_iso2' => 'PS']);
        DB::table('countries')->insert(['country_name' => "Panama", 'country_iso2' => 'PA']);
        DB::table('countries')->insert(['country_name' => "Papua New Guinea", 'country_iso2' => 'PG']);
        DB::table('countries')->insert(['country_name' => "Paraguay", 'country_iso2' => 'PY']);
        DB::table('countries')->insert(['country_name' => "Peru", 'country_iso2' => 'PE']);
        DB::table('countries')->insert(['country_name' => "Philippines", 'country_iso2' => 'PH']);
        DB::table('countries')->insert(['country_name' => "Pitcairn", 'country_iso2' => 'PN']);
        DB::table('countries')->insert(['country_name' => "Poland", 'country_iso2' => 'PL']);
        DB::table('countries')->insert(['country_name' => "Portugal", 'country_iso2' => 'PT']);
        DB::table('countries')->insert(['country_name' => "Puerto Rico", 'country_iso2' => 'PR']);
        DB::table('countries')->insert(['country_name' => "Qatar", 'country_iso2' => 'QA']);
        DB::table('countries')->insert(['country_name' => "RÃ©union", 'country_iso2' => 'RE']);
        DB::table('countries')->insert(['country_name' => "Romania", 'country_iso2' => 'RO']);
        DB::table('countries')->insert(['country_name' => "Russian Federation", 'country_iso2' => 'RU']);
        DB::table('countries')->insert(['country_name' => "Rwanda", 'country_iso2' => 'RW']);
        DB::table('countries')->insert(['country_name' => "Saint BarthÃ©lemy", 'country_iso2' => 'BL']);
        DB::table('countries')->insert(['country_name' => "Saint Helena, Ascension and Tristan da Cunha", 'country_iso2' => 'SH']);
        DB::table('countries')->insert(['country_name' => "Saint Kitts and Nevis", 'country_iso2' => 'KN']);
        DB::table('countries')->insert(['country_name' => "Saint Lucia", 'country_iso2' => 'LC']);
        DB::table('countries')->insert(['country_name' => "Saint Martin (French part)", 'country_iso2' => 'MF']);
        DB::table('countries')->insert(['country_name' => "Saint Pierre and Miquelon", 'country_iso2' => 'PM']);
        DB::table('countries')->insert(['country_name' => "Saint Vincent and the Grenadines", 'country_iso2' => 'VC']);
        DB::table('countries')->insert(['country_name' => "Samoa", 'country_iso2' => 'WS']);
        DB::table('countries')->insert(['country_name' => "San Marino", 'country_iso2' => 'SM']);
        DB::table('countries')->insert(['country_name' => "Sao Tome and Principe", 'country_iso2' => 'ST']);
        DB::table('countries')->insert(['country_name' => "Saudi Arabia", 'country_iso2' => 'SA']);
        DB::table('countries')->insert(['country_name' => "Senegal", 'country_iso2' => 'SN']);
        DB::table('countries')->insert(['country_name' => "Serbia", 'country_iso2' => 'RS']);
        DB::table('countries')->insert(['country_name' => "Seychelles", 'country_iso2' => 'SC']);
        DB::table('countries')->insert(['country_name' => "Sierra Leone", 'country_iso2' => 'SL']);
        DB::table('countries')->insert(['country_name' => "Singapore", 'country_iso2' => 'SG']);
        DB::table('countries')->insert(['country_name' => "Sint Maarten (Dutch part)", 'country_iso2' => 'SX']);
        DB::table('countries')->insert(['country_name' => "Slovakia", 'country_iso2' => 'SK']);
        DB::table('countries')->insert(['country_name' => "Slovenia", 'country_iso2' => 'SI']);
        DB::table('countries')->insert(['country_name' => "Solomon Islands", 'country_iso2' => 'SB']);
        DB::table('countries')->insert(['country_name' => "Somalia", 'country_iso2' => 'SO']);
        DB::table('countries')->insert(['country_name' => "South Africa", 'country_iso2' => 'ZA']);
        DB::table('countries')->insert(['country_name' => "South Georgia and the South Sandwich Islands", 'country_iso2' => 'GS']);
        DB::table('countries')->insert(['country_name' => "South Sudan", 'country_iso2' => 'SS']);
        DB::table('countries')->insert(['country_name' => "Spain", 'country_iso2' => 'ES']);
        DB::table('countries')->insert(['country_name' => "Sri Lanka", 'country_iso2' => 'LK']);
        DB::table('countries')->insert(['country_name' => "Sudan", 'country_iso2' => 'SD']);
        DB::table('countries')->insert(['country_name' => "Suriname", 'country_iso2' => 'SR']);
        DB::table('countries')->insert(['country_name' => "Svalbard and Jan Mayen", 'country_iso2' => 'SJ']);
        DB::table('countries')->insert(['country_name' => "Swaziland", 'country_iso2' => 'SZ']);
        DB::table('countries')->insert(['country_name' => "Sweden", 'country_iso2' => 'SE']);
        DB::table('countries')->insert(['country_name' => "Switzerland", 'country_iso2' => 'CH']);
        DB::table('countries')->insert(['country_name' => "Syrian Arab Republic", 'country_iso2' => 'SY']);
        DB::table('countries')->insert(['country_name' => "Taiwan, Province of China", 'country_iso2' => 'TW']);
        DB::table('countries')->insert(['country_name' => "Tajikistan", 'country_iso2' => 'TJ']);
        DB::table('countries')->insert(['country_name' => "Tanzania, United Republic of", 'country_iso2' => 'TZ']);
        DB::table('countries')->insert(['country_name' => "Thailand", 'country_iso2' => 'TH']);
        DB::table('countries')->insert(['country_name' => "Timor-Leste", 'country_iso2' => 'TL']);
        DB::table('countries')->insert(['country_name' => "Togo", 'country_iso2' => 'TG']);
        DB::table('countries')->insert(['country_name' => "Tokelau", 'country_iso2' => 'TK']);
        DB::table('countries')->insert(['country_name' => "Tonga", 'country_iso2' => 'TO']);
        DB::table('countries')->insert(['country_name' => "Trinidad and Tobago", 'country_iso2' => 'TT']);
        DB::table('countries')->insert(['country_name' => "Tunisia", 'country_iso2' => 'TN']);
        DB::table('countries')->insert(['country_name' => "Turkey", 'country_iso2' => 'TR']);
        DB::table('countries')->insert(['country_name' => "Turkmenistan", 'country_iso2' => 'TM']);
        DB::table('countries')->insert(['country_name' => "Turks and Caicos Islands", 'country_iso2' => 'TC']);
        DB::table('countries')->insert(['country_name' => "Tuvalu", 'country_iso2' => 'TV']);
        DB::table('countries')->insert(['country_name' => "Uganda", 'country_iso2' => 'UG']);
        DB::table('countries')->insert(['country_name' => "Ukraine", 'country_iso2' => 'UA']);
        DB::table('countries')->insert(['country_name' => "United Arab Emirates", 'country_iso2' => 'AE']);
        DB::table('countries')->insert(['country_name' => "United Kingdom", 'country_iso2' => 'GB']);
        DB::table('countries')->insert(['country_name' => "United States", 'country_iso2' => 'US']);
        DB::table('countries')->insert(['country_name' => "United States Minor Outlying Islands", 'country_iso2' => 'UM']);
        DB::table('countries')->insert(['country_name' => "Uruguay", 'country_iso2' => 'UY']);
        DB::table('countries')->insert(['country_name' => "Uzbekistan", 'country_iso2' => 'UZ']);
        DB::table('countries')->insert(['country_name' => "Vanuatu", 'country_iso2' => 'VU']);
        DB::table('countries')->insert(['country_name' => "Venezuela, Bolivarian Republic of", 'country_iso2' => 'VE']);
        DB::table('countries')->insert(['country_name' => "Viet Nam", 'country_iso2' => 'VN']);
        DB::table('countries')->insert(['country_name' => "Virgin Islands, British", 'country_iso2' => 'VG']);
        DB::table('countries')->insert(['country_name' => "Virgin Islands, U.S.", 'country_iso2' => 'VI']);
        DB::table('countries')->insert(['country_name' => "Wallis and Futuna", 'country_iso2' => 'WF']);
        DB::table('countries')->insert(['country_name' => "Western Sahara", 'country_iso2' => 'EH']);
        DB::table('countries')->insert(['country_name' => "Yemen", 'country_iso2' => 'YE']);
        DB::table('countries')->insert(['country_name' => "Zambia", 'country_iso2' => 'ZM']);
        DB::table('countries')->insert(['country_name' => "Zimbabwe", 'country_iso2' => 'ZW']);
    }
}
